---
# Create a new user and add SSH key

- name: Ensure group "admin" exists
  group:
    name: admin
    state: present
  become: yes

- name: Add a user named "{{ server_username }}"
  user:
    name: "{{ server_username }}"
    password: "{{ server_password }}"
    group: admin
    shell: /bin/bash
  become: yes

- name: Create .ssh directory if it does not exist
  file:
    path: "/home/{{ server_username }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ server_username }}"
  become: yes

- name: Add SSH keys to user "{{ server_username }}"
  ansible.builtin.get_url:
    url: "https://github.com/adwinying.keys"
    dest: "~/.ssh/authorized_keys"
    mode: "0600"
    owner: "{{ server_username }}"
  become: yes
