---
# Configure samba share

- name: Install samba package
  apt:
    name: samba
    state: present
    update_cache: yes
  become: yes

- name: Configure samba
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  become: yes
  notify:
    - Restart smbd
