---
# Configure acme.sh

- name: Ensure curl command exists
  apt:
    name: curl
    state: present
    update_cache: yes
  become: yes

- name: Check if .acme.sh folder exists
  stat:
    path: ~/.acme.sh/acme.sh
  register: is_acme_sh_installed

- name: Install acme.sh
  shell: curl https://get.acme.sh | sh
  when: not is_acme_sh_installed.stat.exists

- name: Configure Cloudflare Token
  lineinfile:
    path: ~/.acme.sh/account.conf
    regex: '^SAVED_CF_Token'
    line: SAVED_CF_Token='{{ dns_provider_token }}'
  notify:
    - Issue SSL cert

- name: Configure Cloudflare acccount ID
  lineinfile:
    path: ~/.acme.sh/account.conf
    regex: '^SAVED_CF_Account_ID'
    line: SAVED_CF_Account_ID='{{ dns_provider_account_id }}'
  notify:
    - Issue SSL cert

- name: Create cert directory
  file:
    path: ~/.acme.sh/*.iadw.in
    state: directory
  notify:
    - Issue SSL cert
