---
# SSH settings

- name: Disable root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  become: yes
  notify:
    - Restart sshd

- name: Enable SSH port forwarding outside localhost
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?GatewayPorts"
    line: "GatewayPorts clientspecified"
    state: present
  become: yes
  notify:
    - Restart sshd

- name: Create .ssh directory if it does not exist
  file:
    path: "~/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ server_username }}"

- name: Set SSH private key
  template:
    src: "{{ inventory_hostname }}/id_rsa"
    dest: "~/.ssh/id_rsa"
    mode: "0600"
    owner: "{{ server_username }}"

- name: Set SSH public key
  template:
    src: "{{ inventory_hostname }}/id_rsa.pub"
    dest: "~/.ssh/id_rsa.pub"
    mode: "0644"
    owner: "{{ server_username }}"

- name: Add SSH keys to user "{{ server_username }}"
  ansible.builtin.get_url:
    url: "https://github.com/adwinying.keys"
    dest: "~/.ssh/authorized_keys"
    mode: "0600"
    owner: "{{ server_username }}"
