---
# Set up wireguard

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Enable ProxyARP
  sysctl:
    name: net.ipv4.conf.all.proxy_arp
    value: '1'
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf
  become: yes

- name: Install wireguard
  apt:
    name: wireguard
    state: present
    update_cache: yes
  become: yes

- name: Add wireguard config file
  template:
    src: "{{ wireguard_config_template }}.conf.j2"
    dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
    mode: '0770'
  become: yes
  notify:
    - Restart wireguard service

- name: Create wireguard config directory on remote servers
  file:
    path: "~/wg-conf"
    state: directory
  when: inventory_hostname in groups['remote']

- name: Generate wireguard config file for other peers
  template:
    src: "wg-peer.conf.j2"
    dest: "~/wg-conf/wg-{{ item.name }}.conf"
  when: inventory_hostname in groups['remote']
  loop: "{{ peers }}"

- name: Start wireguard service on boot
  systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    enabled: yes
    masked: no
  become: yes
  notify:
    - Restart wireguard service
